### ISSUE TITLE
A logo for your application

### ISSUE THREAD

**Issue by richardbmx** [mostafa07/gpnt-task#1]
Hello my name is Richard I am a graphic designer and I love making contributions for open source projects, I see that you do not have a defined logo for your application. If you want I can do it for you without any problem you just have to authorize me to do it ... regards. ..

**Comment by mostafa07** [comment]
Hello Richard,
It's just a simple task that I am doing as a selection phase before an interview.
However, if you would not mind and it won't take much of your time, I would be grateful for you if you do it.

**Comment by richardbmx** [comment]
Perfect what is the name of the app ?

**Comment by mostafa07** [comment]
I have not named it actually, but I am thinking about a simple book icon or something like that, but you are totally free to do what you want.

**Comment by richardbmx** [comment]
I present this idea

![logo88](https://user-images.githubusercontent.com/35604837/42136660-ad13127a-7d2d-11e8-91b9-52501e6c3d22.png)

**Comment by mostafa07** [comment]
It's great, I like it.
The name does not really matter. Actually it is counting how many pages a specif user read in one book, so maybe we can give it a simpler name like "Books" or something.
Thank you

**Comment by richardbmx** [comment]
Would it be like that?

![logo882](https://user-images.githubusercontent.com/35604837/42136697-9b50d06c-7d2e-11e8-8122-f8c7078dcf0c.png)

**Comment by mostafa07** [comment]
Yes, This describes it better.
Thank you for your time :)
I would like to be in touch with you for future "bigger" apps.

**Comment by richardbmx** [comment]
clear that if you can contact me by the following email ( richardbmxfx@gmail.com )

I'm going to put together a folder of google drive with all the necessary files so you can use the logo, if you want you can use it from already placing it in the readme file of github

**Comment by mostafa07** [comment]
Yes, go ahead.
You can replace the app icon directly also if you want, and make a pull request.

**Comment by richardbmx** [comment]
I do not know how to do it ...

Here I leave a link with all the necessary files for the use of the logo

[AllFile](https://drive.google.com/open?id=1zeFbZpyNU9OQyDLhWHt7i7NWpAsmpEJs)

**Comment by mostafa07** [comment]
Hey Richard,

I have added the logo as a launcher icon for the app, and also in the README.md file. Feel free to check it after modification.
Again, thank for your efforts, I will close this issue now.
